name = "Shapes"
uuid = "1e37758b-0744-482d-88c6-a60636b43abc"
authors = ["Damian <dcamenisch98@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
